# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.0.0+26.2
maven_group=io.github.kgriff0n
archives_base_name=lambda

# Dependencies
fabric_api_version=0.158.0+26.2
sgui_version=2.1.0+26.2
permission_api_version=0.7.0